"""Historical measurement and field contracts. Do not mutate at runtime."""

COMMON_TAG_KEYS = ("UserId", "Provider", "Device", "DeviceId")

SLEEP_STAGE_MAPPING = {
    "DEEP": (0, "deep"),
    "LIGHT": (1, "light"),
    "REM": (2, "rem"),
    "AWAKE": (3, "awake"),
    "WAKE": (3, "awake"),
    "ASLEEP": (1, "light"),
    "RESTLESS": (2, "rem"),
    "UNKNOWN": (4, "unknown"),
}

FIELD_TYPES: dict[str, dict[str, type]] = {
    "HeartRate_Intraday": {"value": int},
    "RestingHR": {"value": float},
    "HRV": {
        "dailyRmssd": float,
        "deepRmssd": float,
        "nonRemHeartRateBpm": float,
        "entropy": float,
    },
    "HR zones": {
        "Normal": int,
        "Fat Burn": int,
        "Cardio": int,
        "Peak": int,
        "TotalActiveZoneMinutes": int,
    },
    "Steps_Intraday": {"value": int},
    "Total Steps": {"value": float},
    "Activity Minutes": {
        "minutesSedentary": int,
        "minutesLightlyActive": int,
        "minutesFairlyActive": int,
        "minutesVeryActive": int,
        "minutesActiveZone": int,
    },
    "Activity Records": {
        "ActivityId": str,
        "ActiveDuration": int,
        "duration": int,
        "AverageHeartRate": int,
        "calories": int,
        "distance": float,
        "steps": int,
        "startTime": str,
        "endTime": str,
    },
    "calories": {"value": float},
    "distance": {"value": float},
    "GPS": {
        "ActivityId": str,
        "lat": float,
        "lon": float,
        "altitude": float,
        "distance": float,
        "heart_rate": int,
        "speed_kph": float,
    },
    "Sleep Summary": {
        "SleepSessionId": str,
        "efficiency": int,
        "minutesAfterWakeup": int,
        "minutesAsleep": int,
        "minutesAwake": int,
        "minutesDeep": int,
        "minutesInBed": int,
        "minutesLight": int,
        "minutesREM": int,
        "minutesToFallAsleep": int,
        "startTime": str,
        "endTime": str,
    },
    "Sleep Levels": {
        "SleepSessionId": str,
        "level": int,
        "stageName": str,
        "duration_seconds": int,
    },
    "SPO2": {"avg": float, "min": float, "max": float},
    "SPO2_Intraday": {"value": float},
    "BreathingRate": {"value": float},
    "Skin Temperature Variation": {
        "RelativeValue": float,
        "nightlyTemperatureCelsius": float,
        "baselineTemperatureCelsius": float,
        "stddev30d": float,
    },
    "Electrocardiogram": {
        "EcgSessionId": str,
        "resultClassification": str,
        "averageHeartRateBpm": int,
        "samplingFrequencyHertz": int,
        "leadNumber": int,
        "millivoltsScalingFactor": int,
        "sampleCount": int,
        "startTime": str,
        "endTime": str,
        "deviceModel": str,
        "firmwareVersion": str,
        "featureVersion": str,
    },
    "Irregular Rhythm Notifications": {
        "NotificationId": str,
        "potentialAtrialFibrillation": bool,
        "alertWindowCount": int,
        "positiveAlertWindowCount": int,
        "heartBeatCount": int,
        "startTime": str,
        "endTime": str,
        "deviceModel": str,
        "algorithmVersion": str,
        "serviceVersion": str,
    },
    "weight": {"value": float, "weightKg": float, "weightLbs": float},
    "height": {
        "value": float,
        "heightCm": float,
        "heightMeters": float,
        "heightMillimeters": int,
    },
    "bmi": {
        "value": float,
        "weightKg": float,
        "heightMeters": float,
        "isCalculated": bool,
    },
    "Calendar Events": {
        "summary": str,
        "startTime": str,
        "endTime": str,
        "duration_seconds": int,
        "status": str,
        "eventType": str,
        "transparency": str,
        "attendees": int,
        "isOrganizer": bool,
        "responseStatus": str,
        "recurringEventId": str,
        "updated": str,
        "isAllDay": bool,
    },
    "DeviceBatteryLevel": {"value": float},
    "Device Metadata": {
        "deviceName": str,
        "deviceModel": str,
        "timezone": str,
        "lastSyncTime": str,
        "batteryPercent": float,
        "firmwareVersion": str,
        "connectionStatus": str,
    },
}
