"""Provider boundary used by ingestion jobs."""
from typing import Protocol
from app.domain.models import HealthPoint

class HealthProvider(Protocol):
    def fetch_intraday(self, date: str) -> list[HealthPoint]: ...
    def fetch_daily_group(self, group: str, start: str, end: str) -> list[HealthPoint]: ...
    def fetch_workouts(self, end: str | None = None) -> list[HealthPoint]: ...
    def fetch_battery(self) -> list[HealthPoint]: ...
    def fetch_device_metadata(self) -> list[HealthPoint]: ...
    def refresh_credentials(self) -> str: ...
